### ISSUE TITLE
Feature request : Import RDF Graph

### ISSUE THREAD

**Issue by h4ck3rm1k3** [eXascaleInfolab/PyNetConvert#3]
I would like a function to import a RDF graph. 

Here is another implementation :
https://github.com/raghavam/d-sparq , it hashes text into a mongodb and assigns numeric ids to the nodes.

**Comment by luav** [comment]
RDF graph might have multiple links (predicates) from each node (subject) to the same destination node (object), which can't be presented in NSL/NCOL and other formats of this converter without the supervision. You might want to fetch only specific type of links or perform a weighted aggregation.

It might be interesting for you to look at [StaTIX](https://github.com/eXascaleInfolab/StaTIX) (submitted to ISWC-18, I can upload the preprint to ArXiv.org by the request), where we transform RDF graph to the network using cosine similarity and then perform clustering of the network nodes to infer semantic types.
